modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL = "https://github.com/MerchantPug/toomanyorigins/issues"
license="MIT"

[[mods]]
modId = "toomanyorigins"
logoFile="tmo_icon.png"
displayURL="https://github.com/MerchantPug/toomanyorigins/"
version = "${version}"
displayName = "TooManyOrigins"
authors = "MerchantPug"
credits = "Omniv, PapaPepsmAn"
description = '''
Origins addon that serves as an extension to the original mod.
'''

[[dependencies.toomanyorigins]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toomanyorigins]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toomanyorigins]]
modId = "architectury"
mandatory = true
versionRange = "[1.10.142,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.toomanyorigins]]
modId = "origins"
mandatory = true
versionRange = "[0.7.3.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.toomanyorigins]]
modId = "apugli"
mandatory = true
versionRange = "[1.6.2.2,)"
ordering = "AFTER"
side = "BOTH"