modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/MerchantPug/apugli/issues"

[[mods]]
modId="toomanyorigins"
version="${version}"
displayName="TooManyOrigins"
#updateJSONURL=""
displayURL="https://github.com/MerchantPug/toomanyorigins"
logoFile="pack.png"
authors="MerchantPug"
description="An origins addon that adds origins inspired by the base mod."

[[dependencies.toomanyorigins]]
modId="forge"
mandatory=true
versionRange="[40.2.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="origins"
mandatory=true
versionRange="[1.18.2-1.4.1.4,)"
ordering="AFTER"
side="BOTH"