name: Release
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          # Modrinth
          modrinth-id: xDjN28OB
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # CurseForge
          curseforge-id: 469658
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Config
          name: TooManyOrigins v1.0.0-beta.7 (Fabric/Quilt 1.19)
          version: 1.0.0-beta.7+1.19-fabric
          version-type: beta
          changelog-file: CHANGELOG.md
          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: ""

          loaders: |
            fabric
            quilt
          game-versions: |
            1.19
            1.19.1
            1.19.2
          dependencies: |
            fabric-api | depends | *
            origins | depends | *
            apugli | includes | v1.12.0+1.19-fabric
          java: |
            17

          retry-attempts: 2
          retry-delay: 10000

      - name: Publish (GitHub)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          # GitHub
          github-tag: 1.0.0-beta.7+1.19-fabric
          github-draft: false
          github-prerelease: true
          github-commitish: fabric/rework
          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: TooManyOrigins 1.0.0-beta.7 (Fabric/Quilt 1.19)
          version: 1.0.0-beta.7+1.19-fabric
          version-type: beta
          changelog-file: CHANGELOG.md

          loaders: |
            fabric
            quilt
          game-versions: |
            1.19
            1.19.1
            1.19.2
          java: |
            17

          retry-attempts: 2
          retry-delay: 10000